### ISSUE TITLE
福田e家，运行脚本不增加积分，手动进app可以正常签到，没有提示异常

### ISSUE THREAD

**Issue by syhandzp** [msls17/mls#2]
老哥这个可以修吗

**Comment by msls17** [comment]
该情况无法复现，我这边账号正常运行

**Comment by syhandzp** [comment]
可以提供账号密码，就一个邮箱

**Comment by syhandzp** [comment]
> 该情况无法复现，我这边账号正常运行

可以提供账号密码，就一个邮箱

**Comment by msls17** [comment]
将账号密码发送至ms@illii.cn

**Comment by syhandzp** [comment]
> ms@illii.cn
qq邮箱发送失败
账号：18501457607
密码：qq1314521
看完我删了

**Comment by msls17** [comment]
运行并无异常，积分也正常到账。考虑是否你自己的ip，或者运行太频繁的问题

**Comment by syhandzp** [comment]
> 运行并无异常，积分也正常到账。考虑是否你自己的ip，或者运行太频繁的问题

好的多谢，我在试试

**Comment by syhandzp** [comment]
老哥，指导一下怎么添加api代理，我的ip四天就黑了。五个账号，一天运行一次，联通动态公网

**Comment by msls17** [comment]
动态的怎么会黑呀？动态的不是一天一变吗？我这也是动态的ip呀，一天跑25个账号都没问题，我这边反正从来没有这个问题，是不是你账号被风控还是什么的

**Comment by syhandzp** [comment]
> 动态的怎么会黑呀？动态的不是一天一变吗？我这也是动态的ip呀，一天跑25个账号都没问题，我这边反正从来没有这个问题，是不是你账号被风控还是什么的

有时重启光猫IP会变，正常重启ip都不变，即使变了有时候跑了也没积分
怎么看是不是风控了？同一个网络下手动进app没有问题，正常签到，我觉得应该也不是网络的问题
上次账号放你那里跑正常，我才觉得时网络的问题。
注册的时候用了同一个手机 ，不知道这样有没有影响

**Comment by syhandzp** [comment]
> > 动态的怎么会黑呀？动态的不是一天一变吗？我这也是动态的ip呀，一天跑25个账号都没问题，我这边反正从来没有这个问题，是不是你账号被风控还是什么的
> 
> 有时重启光猫IP会变，正常重启ip都不变，即使变了有时候跑了也没积分 怎么看是不是风控了？同一个网络下手动进app没有问题，正常签到，我觉得应该也不是网络的问题 上次账号放你那里跑正常，我才觉得时网络的问题。 注册的时候用了同一个手机 ，不知道这样有没有影响

可以上你的车吗

**Comment by 0711bxk** [comment]
> > > 动态的怎么会黑呀？动态的不是一天一变吗？我这也是动态的ip呀，一天跑25个账号都没问题，我这边反正从来没有这个问题，是不是你账号被风控还是什么的
> > 
> > 
> > 有时重启光猫IP会变，正常重启ip都不变，即使变了有时候跑了也没积分 怎么看是不是风控了？同一个网络下手动进app没有问题，正常签到，我觉得应该也不是网络的问题 上次账号放你那里跑正常，我才觉得时网络的问题。注册的时候用了同一个手机 ，不知道这样有没有影响
> 
> 可以上你的车吗

解决了吗

**Comment by syhandzp** [comment]
> > > > 动态的怎么会黑呀？动态的不是一天一变吗？我这也是动态的ip呀，一天跑25个账号都没问题，我这边反正从来没有这个问题，是不是你账号被风控还是什么的
> > > 
> > > 
> > > 有时重启光猫IP会变，正常重启ip都不变，即使变了有时候跑了也没积分 怎么看是不是风控了？同一个网络下手动进app没有问题，正常签到，我觉得应该也不是网络的问题 上次账号放你那里跑正常，我才觉得时网络的问题。注册的时候用了同一个手机 ，不知道这样有没有影响
> > 
> > 
> > 可以上你的车吗
> 
> 解决了吗

换ip可以  不过福田改加密数据了，库里的的不能做任务了，等老哥修

**Comment by msls17** [comment]
已修复

**Comment by syhandzp** [comment]
> 已修复

没有积分，都是null
是动态的safeKey
